@startuml
skinparam svgDimensionStyle false

title Verifiable Health Links


participant "Trust Anchor" as TA
participant "VHL Holder" as Consume
participant "VHL Receiver" as Request
participant "VHL Sharer" as Sharer

autonumber "<b>00:</b>"


loop routine synchronization 
  Consume -> TA : retrieves and caches all public keys\nfor VHL verification
end
destroy TA

Request -> Sharer  : request VHL enclosing health document\nwith selective disclosure,\ntime limits and passcode
Sharer -> Request : issue and return VHL

Consume -> Sharer : retrieve VHLink Manifest [optional]
Sharer -> Consume : return VHLink Manifest

Consume -> Sharer : retrieve VHLink Clinical Data
Sharer -> Consume : return VHLink Clinical Data




@enduml
