@startuml
skinparam svgDimensionStyle false
hide footbox

participant "VHL Receiver" as Receiver
participant "VHL Sharer" as Sharer

Receiver -> Sharer: Retrieve Manifest Request [ITI-YY5]\nPOST /List/_search\n(authenticated)
Sharer --> Receiver: Retrieve Manifest Response\nFHIR Bundle (searchset)

@enduml
