@startuml
skinparam svgDimensionStyle false
hide footbox

participant "VHL Holder" as Holder
participant "VHL Sharer" as Sharer

Holder -> Sharer: Generate VHL Request [ITI-YY3]
note right
  Request VHL generation
end note

Sharer --> Holder: Generate VHL Response
note left
  Returns VHL as QR code (default) or VC Enveloped VHL
end note

@enduml
