@startuml
skinparam svgDimensionStyle false
hide footbox

participant "VHL Sharer\nor\nVHL Receiver" as Submitter
participant "Trust Anchor" as TA

Submitter -> TA: Submit PKI Material Request [ITI-YY1]

TA --> Submitter: Submit PKI Material Response [ITI-YY1]

@enduml
