@startuml
skinparam svgDimensionStyle false
hide footbox

participant "VHL Holder" as Holder
participant "VHL Receiver" as Receiver

Holder -> Receiver: Provide VHL [ITI-YY4]
Receiver --> Holder: (Optional Acknowledgment)


@enduml
