@startuml
skinparam svgDimensionStyle false
hide footbox
participant "VHL Sharer" as VHLS
participant "Trust Anchor" as TA
participant "VHL Receiver" as VHLR

activate VHLS
activate TA
activate VHLR


VHLS -> TA : Submit PKI Material request [ITI-YY2]
TA -> VHLS : Submit PKI Material response [ITI-YY2]
VHLR -> TA : Submit PKI Material request [ITI-YY2]
TA -> VHLR : Submit PKI Material response [ITI-YY2]


@enduml
