@startuml
skinparam svgDimensionStyle false
hide footbox

participant "VHL Sharer\nor\nVHL Receiver" as Client
participant "Trust Anchor" as TA

Client -> TA: Retrieve Trust List Request [ITI-YY2]
note right
  Request PKI material
  (certificates, keys, CRLs)
end note

TA --> Client: Retrieve Trust List Response [ITI-YY2]
note left
  Trust List with
  validated PKI material
end note

@enduml
