@startuml
skinparam svgDimensionStyle false
hide footbox
participant "VHL Sharer" as VHLS
participant "VHL Holder" as VHLH

activate VHLH
activate VHLS


VHLH -> VHLS : Generate VHL request [ITI-YY1]
VHLS -> VHLH : Generate VHL response [ITI-YY1]


@enduml
