Feature: ITI-YY3 Generate VHL – Security Considerations
  Security requirements for the Generate VHL transaction, covering transport
  security, passcode protection, cryptographic key entropy, and PHI exclusion.

  # ─── Transport Security ───────────────────────────────────────────────────────

  @security @SHALL
  Scenario: $generate-vhl request is transmitted over HTTPS
    Given the VHL Holder is sending the Generate VHL request
    When the connection is established
    Then the request SHALL use HTTPS
    And plain HTTP SHALL NOT be used

  # ─── Passcode Security ───────────────────────────────────────────────────────

  @security @SHALL
  Scenario: Passcode is never stored in plaintext by the VHL Sharer
    Given the VHL Sharer receives a $generate-vhl request with a passcode
    When the passcode is processed
    Then the VHL Sharer SHALL hash it before storage using bcrypt, Argon2, or PBKDF2
    And the plaintext passcode SHALL NOT be retained in any persistent storage

  @security @SHALL
  Scenario: Passcode is never embedded in the QR code or VHL URL
    Given a passcode was provided in the request
    When the QR code and VHL URL are generated
    Then the plaintext passcode SHALL NOT appear in the QR code content
    And the plaintext passcode SHALL NOT appear in the VHL URL

  @security @SHALL
  Scenario: VHL Holder transmits the passcode to the VHL Receiver over a secure out-of-band channel
    Given the VHL Holder needs to share the passcode with an authorised VHL Receiver
    When the passcode is communicated
    Then the VHL Holder SHALL use a secure out-of-band transmission method

  # ─── Cryptographic Key Entropy ───────────────────────────────────────────────

  @security @SHALL
  Scenario: Folder ID has at least 256 bits of entropy
    When the folder ID is generated for a new VHL
    Then the folder ID SHALL have at least 256 bits of entropy

  @security @SHALL
  Scenario: Encryption key is generated by a cryptographically secure random number generator
    When the 32-byte encryption key is generated
    Then it SHALL be produced by a cryptographically secure random number generator

  # ─── PHI Exclusion ───────────────────────────────────────────────────────────

  @security @SHALL
  Scenario: The generated QR code contains no protected health information
    When the QR code payload is inspected
    Then the QR code SHALL NOT contain any PHI
    And it SHALL contain only a reference URL and authorization metadata (SHL payload)
