Feature: ITI-YY3 Generate VHL Response
  As a VHL Sharer (Responder)
  I want to generate and return a QR code containing a signed HCERT-encoded VHL
  So that the VHL Holder can present it to VHL Receivers to authorize document retrieval

  Background:
    Given the VHL Sharer has received a valid $generate-vhl request
    And the VHL Sharer has access to its private signing key and DSC

  # ─── Success Response Structure ───────────────────────────────────────────────

  Scenario: VHL Sharer returns HTTP 200 with a Binary QR code parameter on success
    Given a well-formed $generate-vhl request is received with a valid sourceIdentifier
    When the VHL Sharer processes the request
    Then the response SHALL be HTTP 200 OK
    And the response SHALL include a FHIR Parameters resource
    And the output parameter "qrcode" SHALL be of type Binary

  Scenario: QR code output is in PNG or SVG format
    Given the VHL Sharer has generated a QR code
    When the "qrcode" Binary output is inspected
    Then the content type SHALL be "image/png" or "image/svg+xml"

  Scenario: QR code is encoded with the HC1: prefix
    Given the VHL Sharer has generated the HCERT structure
    When the QR code content is decoded
    Then the encoded string SHALL begin with the prefix "HC1:"

  Scenario: QR code uses alphanumeric mode per ISO/IEC 18004:2015
    Given the VHL Sharer is generating the QR code
    When the QR code is produced
    Then the QR code SHALL use Alphanumeric mode (Mode 2) per ISO/IEC 18004:2015

  Scenario: QR code uses error correction level Q
    Given the VHL Sharer is generating the QR code
    When the QR code is produced
    Then the error correction level SHALL be Q (25% recovery)

  # ─── Passcode Handling ───────────────────────────────────────────────────────

  Scenario: VHL Sharer hashes the passcode before storage when passcode is provided
    Given the $generate-vhl request includes "passcode=secretpin"
    When the VHL Sharer processes the request
    Then the VHL Sharer SHALL hash the passcode using a strong one-way function (bcrypt, Argon2, or PBKDF2)
    And the VHL Sharer SHALL store the hashed passcode associated with the generated folder ID

  Scenario: Plaintext passcode is never stored by the VHL Sharer
    Given the $generate-vhl request includes "passcode=secretpin"
    When the VHL Sharer processes the passcode
    Then the VHL Sharer SHALL NOT retain the plaintext passcode in persistent storage

  Scenario: P flag is included in the SHL payload when a passcode is provided
    Given the $generate-vhl request includes a passcode
    When the SHL payload is constructed
    Then the "flag" field in the SHL payload SHALL include the "P" character

  # ─── VHL Payload Construction ────────────────────────────────────────────────

  Scenario: VHL Sharer generates a unique folder ID with 256-bit entropy
    Given the VHL Sharer is processing a VHL generation request
    When the folder ID is created
    Then the folder ID SHALL have at least 256 bits of entropy

  Scenario: VHL Sharer generates a 32-byte random encryption key
    Given the VHL Sharer is processing a VHL generation request
    When the encryption key is generated
    Then the key SHALL be 32 bytes (256 bits) generated by a cryptographically secure random number generator
    And the key SHALL be base64url-encoded to produce exactly 43 characters

  Scenario: SHL payload url field is present and contains the manifest URL
    Given the VHL Sharer has generated a folder ID "abc123def456"
    When the SHL payload is constructed
    Then the "url" field SHALL be present
    And the "url" SHALL be an HTTPS URL pointing to the List resource for that folder

  Scenario: Manifest URL includes all mandatory FHIR search parameters
    Given the VHL Sharer is constructing the manifest URL
    When the URL is assembled
    Then the URL SHALL include the "_id" parameter set to the folder ID
    And the URL SHALL include the "code" parameter set to "folder"
    And the URL SHALL include the "status" parameter set to "current"
    And the URL SHALL include the "patient.identifier" parameter with the patient's identifier in "system|value" format

  Scenario: Manifest URL includes _include=List:item when Include DocumentReference Option is supported
    Given the VHL Sharer supports the Include DocumentReference Option
    When the manifest URL is constructed
    Then the URL SHALL include "_include=List:item"

  Scenario: Manifest URL does not include _include when Include DocumentReference Option is not supported
    Given the VHL Sharer does NOT support the Include DocumentReference Option
    When the manifest URL is constructed
    Then the URL SHALL NOT include the "_include" parameter

  Scenario: SHL payload key field is the 43-character base64url-encoded encryption key
    Given the VHL Sharer has generated a 32-byte encryption key
    When the SHL payload "key" field is set
    Then the "key" value SHALL be exactly 43 characters
    And the value SHALL be valid base64url encoding

  Scenario: SHL payload version field defaults to 1
    Given the VHL Sharer is constructing the SHL payload
    When the "v" field is set
    Then the "v" field SHALL default to 1

  # ─── HCERT/CWT Encoding ──────────────────────────────────────────────────────

  Scenario: CWT protected header specifies a permitted signing algorithm
    Given the VHL Sharer is creating the CWT protected header
    When the "alg" field is set
    Then the algorithm SHALL be "ES256" (primary) or "PS256" (secondary)

  Scenario: CWT protected header includes the key identifier (kid)
    Given the VHL Sharer has a DSC (Document Signing Certificate)
    When the CWT protected header is assembled
    Then the "kid" field SHALL be set to the first 8 bytes of the SHA-256 fingerprint of the DSC

  Scenario: CWT claims include issued-at timestamp
    Given the VHL Sharer is assembling CWT claims
    When the "iat" claim (claim key 6) is set
    Then the value SHALL be the current time in NumericDate format
    And the "iat" SHALL NOT be in the future

  Scenario: CWT claims include expiration timestamp when exp is provided
    Given the $generate-vhl request includes "exp=1735689600"
    When the CWT claims are assembled
    Then the "exp" claim (claim key 4) SHALL be set to 1735689600 in NumericDate format

  Scenario: SHL payload is embedded in CWT hcert claim at claim key 5
    Given the VHL Sharer has constructed the SHL payload
    When the CWT "hcert" claim (claim key -260) is assembled
    Then the SHL payload SHALL be placed at claim key 5 within the hcert object

  Scenario: CWT is signed using COSE with the VHL Sharer's private key
    Given the CWT structure has been assembled
    When the signing step is performed
    Then the CWT SHALL be signed using COSE (RFC 8152) with the VHL Sharer's private key

  Scenario: Signed CWT is compressed using ZLIB with DEFLATE
    Given the CWT has been signed
    When the compression step is performed
    Then the signed CWT SHALL be compressed using ZLIB (RFC 1950) with DEFLATE (RFC 1951)

  Scenario: Compressed CWT is encoded as Base45
    Given the signed CWT has been ZLIB-compressed
    When the encoding step is performed
    Then the compressed bytes SHALL be encoded using Base45

  Scenario: Encoded payload is prefixed with HC1:
    Given the Base45-encoded payload is ready
    When the context identifier is prepended
    Then the final string SHALL begin with "HC1:"

  # ─── Error Responses ─────────────────────────────────────────────────────────

  Scenario: VHL Sharer returns HTTP 4xx with OperationOutcome when sourceIdentifier resolves no patient
    Given the "sourceIdentifier" in the request does not match any known patient
    When the VHL Sharer attempts to process the request
    Then the response SHALL be an HTTP 4xx status code
    And the response body SHALL be a FHIR OperationOutcome with error details

  Scenario: VHL Sharer returns HTTP 4xx with OperationOutcome for a missing required parameter
    Given the $generate-vhl request is missing the "sourceIdentifier" parameter
    When the VHL Sharer evaluates the request
    Then the response SHALL be HTTP 400 Bad Request
    And the response body SHALL be a FHIR OperationOutcome indicating the missing parameter

  Scenario: VHL Sharer returns HTTP 5xx with OperationOutcome for internal server errors
    Given an internal error occurs during VHL generation
    When the VHL Sharer handles the error
    Then the response SHALL be an HTTP 5xx status code
    And the response body SHALL be a FHIR OperationOutcome with the error description
